### ISSUE TITLE
Blood Ritual, Dead Runes

### ISSUE THREAD

**Issue by ujvaribalint** [CutFuyi/JS13KGAMES-2022---Idle-Necromancer#1]
How Blood Ritual works is not that self explanatory

**Comment by CutFuyi** [comment]
Hi,

To perform a bloody ritual you must use the bloody ritual card (you have to
light all the candles by clicking several times, the candles go out after a
while), if you have a max in rank III then you should already have it (if
you don't have it despite the max then we have a problem), the dead rune
card increases the playing field, at the start you have two columns of
space less.
And thanks for spotting the language error :)

śr., 31 sie 2022 o 19:49 ujvaribalint ***@***.***> napisał(a):

**Comment by ujvaribalint** [comment]
Hey,
Thanks for the answer. I didn't notice that the bloody ritual's candles get lit when I click them. My bad. I actually quite like the mysterious aspect of the game, that you have to figure stuff out.
Nice game. Had a couple of bloody rituals now.  : )
